source 'https://rubygems.org'
gem "bundler"
gem "jekyll"
gem "jekyll-paginate"
gem 'jekyll-tagging'
gem "jekyll-sitemap"

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# https://github.com/jekyll/jekyll/issues/8523
gem "webrick", "~> 1.7"